"""
Audit: what does the LVDAndro row in Table 4 actually measure?

WHY THIS EXISTS
---------------
Reading the LVDAndro paper (Senanayake et al., SECRYPT 2023) surfaced two facts
that are not visible from our JSONL alone:

  1. LVDAndro's labels are the union of MobSF and QARK findings. Both are
     signature-based scanners; the authors say so themselves.
  2. LVDAndro is a LINE-level corpus. Using it at function level needs a
     windowing step -- ours is `lvdprocess.py`, window_radius=5.

That combination predicts a lexical shortcut, and predicts that our windows are
malformed. This script tests both on the exact filtered test partition behind
PAPER.md Table 4, so the claim in PAPER.md §3.5b is reproducible rather than
asserted.

USAGE
    python test_scripts/audit_lvdandro_shortcut.py
    python test_scripts/audit_lvdandro_shortcut.py --data dataset/dataset_graphcodebert.jsonl

OUTPUT  results/lvdandro_shortcut_audit.txt
"""

import argparse
import json
import os
import re
import sys
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from split_and_filter import get_split_indices, source_for_reporting

LOG_CALL = re.compile(r'\bLog\.[vdiwe]\s*\(')


def brace_balanced(code):
    """Weak necessary condition for parseability. Cheap, and enough to show the gap."""
    depth = 0
    for ch in code:
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth < 0:
                return False
    return depth == 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default='dataset/dataset_graphcodebert.jsonl')
    ap.add_argument('--out', default='results/lvdandro_shortcut_audit.txt')
    a = ap.parse_args()

    _, _, test_idx, _ = get_split_indices(a.data)
    test_idx = set(test_idx)

    per = defaultdict(Counter)
    with open(a.data, encoding='utf-8', errors='replace') as f:
        for i, line in enumerate(f):
            if i not in test_idx:
                continue
            d = json.loads(line)
            s = source_for_reporting(d.get('filename'))
            code = d.get('code') or ''
            label = d.get('label')
            c = per[s]
            c['n'] += 1
            c['balanced'] += brace_balanced(code)
            c['vuln'] += (label == 1)
            has_log = bool(LOG_CALL.search(code))
            c['log'] += has_log
            c[f'log{int(has_log)}_label{label}'] += 1

    out = []
    w = out.append
    w('LVDAndro shortcut + well-formedness audit')
    w('=' * 78)
    w(f'Data       : {a.data}')
    w(f'Partition  : canonical split, duplicate-filtered test set '
      f'({sum(c["n"] for c in per.values()):,} rows)')
    w('Reference  : PAPER.md 3.5b, 8b.5, L2.3, L2.7')
    w('')
    w('Per-source well-formedness and Log.x() prevalence')
    w('-' * 78)
    w(f'{"source":10s} {"n":>7s} {"vuln%":>8s} {"brace-balanced":>16s} {"has Log.x()":>13s}')
    for s, c in sorted(per.items(), key=lambda kv: -kv[1]['n']):
        w(f'{s:10s} {c["n"]:7,d} {100*c["vuln"]/c["n"]:7.2f}% '
          f'{100*c["balanced"]/c["n"]:15.1f}% {100*c["log"]/c["n"]:12.1f}%')
    w('')
    w('The single-rule baseline:  "contains Log.x()  =>  vulnerable"')
    w('-' * 78)
    for s, c in sorted(per.items(), key=lambda kv: -kv[1]['n']):
        tp, fp = c['log1_label1'], c['log1_label0']
        fn, tn = c['log0_label1'], c['log0_label0']
        if tp + fp == 0:
            w(f'{s:10s} no Log.x() calls in this source -- rule inapplicable')
            continue
        w(f'{s:10s} with Log   : {tp+fp:6,d} rows, {100*tp/(tp+fp):5.1f}% vulnerable')
        w(f'{"":10s} without    : {fn+tn:6,d} rows, {100*fn/max(1,fn+tn):5.1f}% vulnerable')
        w(f'{"":10s} RULE ACCURACY = {100*(tp+tn)/c["n"]:.2f}%   (no model involved)')
    w('')
    w('For comparison, fine-tuned GraphCodeBERT text-only on the LVDAndro subset')
    w('scores 97.5408% (PAPER.md Table 4). The gap over the regex is ~15 points,')
    w('not ~97 -- which is the honest way to report that row.')
    w('')
    w('Provenance: generated by test_scripts/audit_lvdandro_shortcut.py')

    text = '\n'.join(out)
    print(text)
    os.makedirs(os.path.dirname(a.out) or '.', exist_ok=True)
    with open(a.out, 'w', encoding='utf-8') as f:
        f.write(text + '\n')
    print(f'\nSaved -> {a.out}')


if __name__ == '__main__':
    main()
